POST http://localhost:3000/metricas HTTP/1.1
content-type: application/json

{
    "id_metrica": "780208983319937026",
    "coverage":5.5,
    "bugs":35,
    "vulnerabilities":25,
    "hotspot":4,
    "code_smells":23
}


